name: Postman Collection workflow

on:
  push: 
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * 
    - cron: 00 17 * * *
    - cron: 00 06 * * 1-5

jobs:
  run-postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code / get code
        uses: actions/checkout@v6.0.2

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 22

      - name: Install Newman and Html-extra globally
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run the Postman collection with newman
        run: | 
             newman run 'In-WarrantyFlow Collection_Ext_CSV.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,htmlextra 
             
             
              
              
          
            
            
        
        
      
    
    
    
    
    
  
    
