name: Postman Collection workflow

on:
  push: 
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * * 
    - cron: 45 05 * * *
    - cron: 00 06 * * 1-5

jobs:
  run-postman-test:
    runs-on: ec2-github-runner

    steps:
      - name: checkout the code / get code
        uses: actions/checkout@v6.0.2

      - name: Install Nodejs and npm
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 22

      - name: Install Newman and Html-extra globally
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run the Postman collection with newman
        run: | 
             newman run 'In-WarrantyFlow Collection_Ext_CSV.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testData.csv \
             -r cli,htmlextra \
             --reporter-htmlextra-export ./newman/index.html  

      - name: Newman Report
        if: always()     # it ensures  that archived executes irrespective of previous steps has passed or Not
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Newman report
          path: newman/*.html
      
      - name: Creating GitHub page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
      
      - name: Sending Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v9
        with:
          server_address: smtp.gmail.com
          server-port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }} # Not Gmail pass , use app password
          subject: Phoenix Inwarrenty flow Test Execution Notification
          to: sundarkande445@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
                 Hi , 
                 Phenoix Inwarranty Flow has been executed . The report has beedn published and the
                 URL is : https://sundar10121992.github.io/Phoenix-Inwarranty-Flow/
          
          
          
          
          
          
          

        
        
            
        
        
              
          
            
            
        
        
      
    
    
    
    
    
  
    
